const songs = [
  {
    id: 1,
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    cover: "https://picsum.photos/400/400?random=1",
    audio: "#",
    duration: "4:22",
  },
  {
    id: 2,
    title: "Channa Mereya",
    artist: "Arijit Singh",
    cover: "https://picsum.photos/400/400?random=2",
    audio: "#",
    duration: "4:49",
  },
  {
    id: 3,
    title: "Kesariya",
    artist: "Arijit Singh",
    cover: "https://picsum.photos/400/400?random=3",
    audio: "#",
    duration: "3:17",
  },
  {
    id: 4,
    title: "Raatan Lambiyan",
    artist: "Jubin Nautiyal",
    cover: "https://picsum.photos/400/400?random=4",
    audio: "#",
    duration: "3:50",
  },
  {
    id: 5,
    title: "Mann Mera",
    artist: "Gajendra Verma",
    cover: "https://picsum.photos/400/400?random=5",
    audio: "#",
    duration: "3:14",
  },
  {
    id: 6,
    title: "Tere Hawaale",
    artist: "Arijit Singh",
    cover: "https://picsum.photos/400/400?random=6",
    audio: "#",
    duration: "4:30",
  },
  {
    id: 7,
    title: "Phir Aur Kya Chahiye",
    artist: "Arijit Singh",
    cover: "https://picsum.photos/400/400?random=7",
    audio: "#",
    duration: "4:26",
  },
  {
    id: 8,
    title: "Tere Vaaste",
    artist: "Sachin-Jigar",
    cover: "https://picsum.photos/400/400?random=8",
    audio: "#",
    duration: "3:09",
  },
  {
    id: 9,
    title: "Pasoori Nu",
    artist: "Arijit Singh",
    cover: "https://picsum.photos/400/400?random=9",
    audio: "#",
    duration: "3:17",
  },
  {
    id: 10,
    title: "Tere Pyaar Mein",
    artist: "Arijit Singh",
    cover: "https://picsum.photos/400/400?random=10",
    audio: "#",
    duration: "4:26",
  },
];
